version: "3.9"

services:
  web:
    container_name: examination-app
    image: examination-app:v1
    build: .
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/examination_app
    depends_on:
      - db
    networks:
      - postgres
    ports:
      - "8080:8080"

  db:
    container_name: postgres-db
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: dhoang
      POSTGRES_PASSWORD: pass
    networks:
      - postgres
    ports:
      - "5432:5432"

#  adminer:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    restart: unless-stopped
#    ports:
#      - 5050:80
#    networks:
#      - postgres

networks:
  postgres:
    driver: bridge